#!/bin/tcsh

# Usage cstat <pattern> [n]
# n defaults to 3

if ( $#argv > 2 || $#argv == 0 ) then
    echo
    echo "Usage: cstat <pattern> [n]"
    echo "       n defaults to 3"
    echo
    exit
endif 

set n = "3"

if ( $#argv == 2 ) then
    set n = $2    
endif

cd ${COLOMBE_ROOT}/exp

foreach the_dir ( $1 )
    echo
    echo $the_dir
    grep "accuracy =" ${the_dir}/stdout_log | tail -${n}
end

foreach the_dir ( $1 )
    echo
    echo $the_dir
    grep "Iteration.*loss =" ${the_dir}/stdout_log | tail -${n}
end

