#!/bin/tcsh

# Usage cstat [n]
# n defaults to 3

if ( $#argv > 1 ) then
    echo
    echo "Usage: cstat [n]"
    echo "       n defaults to 3"
    echo
    exit
endif 

set n = "3"

if ( $#argv == 1 ) then
    set n = $1    
endif

foreach the_file ( `find ${COLOMBE_ROOT}/exp -name stdout_log | sort` )
echo
echo $the_file
grep "accuracy =" $the_file | tail -${n}
end
